name: Clang format
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.11
      with:
        source: '.'
        exclude: './pio'
        extensions: 'h,cpp'
        clangFormatVersion: 11
        style: chromium
